const mongoose = require("mongoose");
const Campground = require("../models/campground");
const cities = require("./cities");
const { descriptors, places } = require("./seedHelpers");

const mapboxToken = "pk.eyJ1IjoiZXJheWdvbiIsImEiOiJjbGtzM2h6aGIzOGNwM3BrZ211eDdsZ2cxIn0.atFUv500LrTUT7NeBYBkWg";
const mbxGeocoding = require('@mapbox/mapbox-sdk/services/geocoding');
const geoCoder = mbxGeocoding({ accessToken: mapboxToken });


// declare global {
//     var fetch: typeof nodeFetch.default;
//     type RequestInit = nodeFetch.RequestInit;
//     type Response = nodeFetch.Response;
// }
// global.fetch = nodeFetch.default;

mongoose.connect('mongodb://127.0.0.1:27017/camp-scape');

const db = mongoose.connection; // Connection object represents the connection to the MongoDB database.

db.on("error", console.error.bind(console, "connection error:"));
// bind() method allows you to create a new function with a specific context (the value of this)
//   and optionally pre-set arguments. 

db.once("open", () => {
    console.log("Database Connected");
});

const sample30 = Math.floor(Math.random() * 20 + 10);

const sample = array => array[Math.floor(Math.random() * array.length)];

const obj = [
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/nzobvzrryxwumq89qpvf'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/bbbil8tvlcc9qe5ukeyi'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/twdlnvkd2be4intmgfqq'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/q6kbiiqbgyvh91sbptpm'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/yhwurmqtvoln9rtmswio'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/inc4jdciues9urke6qj8'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/cbnbz0i9hqazhtqoagap'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/epd6nqs6h6qokh5kjc6s'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/iuvjgygxukgmmmlepyg8'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/ud8f2lvcap6hpzjcg1f2'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/eorsddu1copfgwr4bdgj'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/byuufyixd8ms1oj0nrvr'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/orgebmoclnvnsy7prbck'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/cf85v3zhxnfif0zkcgfn'
    },
    {
        url: 'https://res.cloudinary.com/djs1tvguk/image/upload/v1691045829/SeededCamps/g14w82uj6uvsfzhxfn2v.jpg',
        filename: 'CampScape/yqosjlfpyreylh8ljofq'
    }
];

const loc = [
    "Spiti Valley, Himachal Pradesh",
    "Chandratal Lake, Himachal Pradesh",
    "Solang Valley, Manali",
    "Tso Moriri, Ladakh",
    "Rishikesh, Uttarakhand",
    "Mussoorie, Uttarakhand",
    "Nameri Eco Camp, Assam",
    "Anjuna beach, Goa",
    "Sam Sand Dunes, Jaisalmer",
    "Neora Valley Camp, West Bengal",
    "Srinagar, Jammu & Kashmir",
    "Pahalgam, Jammu & Kashmir",
    "Gulmarg, Jammu & Kashmir",
    "Manali, Himachal Pradesh",
    "Khajjiar, Himachal Pradesh",
    "Keylong, Himachal Pradesh",
    "Bir Billing, Himachal Pradesh",
    "Shimla, Himachal Pradesh",
    "McLeodganj, Himachal Pradesh",
    "Almora, Uttarakhand",
    "Nainital, Uttarakhand",
    "Auli, Uttarakhand",
    "Kausani, Uttarakhand",
    "Chopta, Uttarakhand",
    "Tawang, Arunachal Pradesh",
    "Bomdila, Arunachal Pradesh",
    "Mirik, West Bengal",
    "Darjeeling, West Bengal",
    "Kalimpong, West Bengal",
    "Champhai, Mizoram",
    "Aizawl, Mizoram",
    "Gangtok, Sikkim",
    "Pelling, Sikkim",
    "Shillong, Meghalaya",
    "Cherrapunji, Meghalaya",
    "Mount Abu, Rajasthan",
    "Wilson Hills, Gujarat",
    "Saputara, Gujarat",
    "Pachmarhi, Madhya Pradesh",
    "Amarkantak, Madhya Pradesh",
    "Panchgani, Maharasthra",
    "Matheran, Maharashtra",
    "Mahabaleshwar, Maharashtra",
    "Amboli, Maharashtra",
    "Daringbadi, Orissa",
    "Coorg, Karnataka",
    "Kudremukh, Karnataka",
    "Agumbe, Karnataka",
    "Araku Valley, Andhra Pradesh",
    "Ananthagiri Hills, Andhra Pradesh",
    "Horsley Hills, Andhra Pradesh",
    "Lambasingi, Andhra Pradesh",
    "Munnar, Kerala",
    "Thekkady, Kerala",
    "Ooty, Tamil Nadu",
    "Kodaikanal, Tamil Nadu",
    "Yercaud , Tamil Nadu",
    "Kotagiri, Tamil Nadu",
    "Kolli Hills, Tamil Nadu",
    "Meghamalai, Tamil Nadu",
    "Ladakh, Jammu & Kashmir",
    "Mussoorie, Uttarakhand",
    "Lonavala, Maharashtra",
    "Dharamshala, Himachal Pradesh",
    "Chikmagalur, Karnataka",
    "Valparaj, Tamil Nadu",
    "Champawat, Uttarakhand",
    "Kurseong, West Bengal",
    "Joginder Nagar, Himachal Pradesh",
    "Dharamkot, Himachal Pradesh",
    "Yosemite National Park, California",
    "Grand Canyon National Park, Arizona",
    "Yellowstone National Park, Wyoming",
    "Acadia National Park, Maine",
    "Glacier National Park, Montana",
    "Zion National Park, Utah",
    "Great Smoky Mountains National Park, Tennessee/North Carolina",
    "Rocky Mountain National Park, Colorado",
    "Olympic National Park, Washington",
    "Joshua Tree National Park, California",
    "Bryce Canyon National Park, Utah",
    "Sequoia and Kings Canyon National Parks, California",
    "Shenandoah National Park, Virginia",
    "Arches National Park, Utah",
    "Mount Rainier National Park, Washington",
    "Death Valley National Park, California/Nevada",
    "Redwood National and State Parks, California",
    "Big Bend National Park, Texas",
    "Grand Teton National Park, Wyoming",
    "Everglades National Park, Florida",
    "Canyonlands National Park, Utah",
    "Denali National Park and Preserve, Alaska",
    "Mammoth Cave National Park, Kentucky",
    "Haleakalā National Park, Hawaii",
    "Cuyahoga Valley National Park, Ohio",
    "Badlands National Park, South Dakota",
    "White Mountain National Forest, New Hampshire",
    "Mount Hood National Forest, Oregon",
    "Olympic National Forest, Washington",
    "Chattahoochee National Forest, Georgia",
    "Coconino National Forest, Arizona",
    "Uinta-Wasatch-Cache National Forest, Utah",
    "San Bernardino National Forest, California",
    "Gifford Pinchot National Forest, Washington",
    "Eldorado National Forest, California",
    "Tonto National Forest, Arizona",
    "Shoshone National Forest, Wyoming",
    "Black Hills National Forest, South Dakota",
    "Pisgah National Forest, North Carolina",
    "Chugach National Forest, Alaska",
    "Okanogan-Wenatchee National Forest, Washington",
    "Lassen National Forest, California",
    "Sierra National Forest, California",
    "Tongass National Forest, Alaska",
    "Inyo National Forest, California",
    "Nantahala National Forest, North Carolina",
    "Sawtooth National Forest, Idaho",
    "Ashley National Forest, Utah",
    "Daniel Boone National Forest, Kentucky",
    "Stanislaus National Forest, California",
    "Klamath National Forest, California",
    "Chequamegon-Nicolet National Forest, Wisconsin",
    "Roosevelt National Forest, Colorado",
    "Gila National Forest, New Mexico",
    "Bighorn National Forest, Wyoming",
    "Nez Perce-Clearwater National Forests, Idaho",
    "Carson National Forest, New Mexico",
    "Mendocino National Forest, California",
    "Lolo National Forest, Montana",
    "Wallowa-Whitman National Forest, Oregon",
    "Flathead National Forest, Montana",
    "Superior National Forest, Minnesota",
    "Custer Gallatin National Forest, Montana",
    "Deschutes National Forest, Oregon",
    "Malheur National Forest, Oregon",
    "Lolo National Forest, Montana",
    "Arapaho National Forest, Colorado",
    "Boise National Forest, Idaho",
    "Prescott National Forest, Arizona",
    "Humboldt-Toiyabe National Forest, Nevada",
    "Lewis and Clark National Forest, Montana",
    "Helena National Forest, Montana",
    "Shasta-Trinity National Forest, California",
    "Apache-Sitgreaves National Forest, Arizona",
    "Gunnison National Forest, Colorado",
    "Pike National Forest, Colorado",
    "Manti-La Sal National Forest, Utah",
    "Santa Fe National Forest, New Mexico",
    "Lander National Forest, Wyoming",
    "Salmon-Challis National Forest, Idaho",
    "Wichita Mountains Wildlife Refuge, Oklahoma",
    "Flathead National Forest, Montana",
    "Sawtooth National Forest, Idaho",
    "El Yunque National Forest, Puerto Rico",
    "Payette National Forest, Idaho",
    "Ouachita National Forest, Arkansas/Oklahoma",
    "Black Hills National Forest, South Dakota",
    "Stanislaus National Forest, California",
    "Vermilion Cliffs National Monument, Arizona",
    "Siuslaw National Forest, Oregon",
    "Cleveland National Forest, California",
    "Tahoe National Forest, California",
    "Pisgah National Forest, North Carolina",
    "Siuslaw National Forest, Oregon",
    "Tuskegee National Forest, Alabama",
    "Uinta-Wasatch-Cache National Forest, Utah",
    "Coconino National Forest, Arizona",
    "Hoosier National Forest, Indiana",
    "Arapaho National Forest, Colorado",
    "Pike National Forest, Colorado",
    "Superior National Forest, Minnesota",
    "Chippewa National Forest, Minnesota",
    "Dixie National Forest, Utah",
    "Ottawa National Forest, Michigan",
    "Hiawatha National Forest, Michigan",
    "Tahoe National Forest, California",
    "Lake Tahoe Basin Management Unit, California/Nevada",
    "Idaho Panhandle National Forests, Idaho",
    "Plumas National Forest, California",
    "Lolo National Forest, Montana",
    "Sawtooth National Forest, Idaho",
    "Superstition Wilderness, Arizona",
    "Custer Gallatin National Forest, Montana",
    "Chequamegon-Nicolet National Forest, Wisconsin",
    "Arapaho National Forest, Colorado",
    "Gunnison National Forest, Colorado",
    "Flathead National Forest, Montana",
    "Salmon-Challis National Forest, Idaho",
    "El Yunque National Forest, Puerto Rico",
    "Payette National Forest, Idaho",
    "Ouachita National Forest, Arkansas/Oklahoma",
    "Vermilion Cliffs National Monument, Arizona",
    "Siuslaw National Forest, Oregon",
    "Cleveland National Forest, California",
    "Tahoe National Forest, California",
    "Pisgah National Forest, North Carolina",
    "Siuslaw National Forest, Oregon",
    "Tuskegee National Forest, Alabama",
    "Uinta-Wasatch-Cache National Forest, Utah",
    "Coconino National Forest, Arizona",
    "Hoosier National Forest, Indiana",
    "Arapaho National Forest, Colorado",
    "Pike National Forest, Colorado",
    "Superior National Forest, Minnesota",
    "Chippewa National Forest, Minnesota",
    "Dixie National Forest, Utah",
    "Ottawa National Forest, Michigan",
    "Hiawatha National Forest, Michigan",
    "Tahoe National Forest, California",
    "Lake Tahoe Basin Management Unit, California/Nevada",
    "Idaho Panhandle National Forests, Idaho",
    "Plumas National Forest, California",
    "El Yunque National Forest, Puerto Rico",
    "Tahoe National Forest, California",
    "Lake Tahoe Basin Management Unit, California/Nevada",
    "Idaho Panhandle National Forests, Idaho",
    "Plumas National Forest, California",
    "El Yunque National Forest, Puerto Rico",
    "Lassen Volcanic National Park, California",
    "Kings Canyon National Park, California",
    "Guadalupe Mountains National Park, Texas",
    "Capitol Reef National Park, Utah",
    "Cape Hatteras National Seashore, North Carolina",
    "Congaree National Park, South Carolina",
    "Cumberland Island National Seashore, Georgia",
    "Dry Tortugas National Park, Florida",
    "Gateway National Recreation Area, New York/New Jersey",
    "Glen Canyon National Recreation Area, Arizona/Utah",
    "Gulf Islands National Seashore, Florida/Mississippi",
    "Indiana Dunes National Park, Indiana",
    "Isle Royale National Park, Michigan",
    "Mammoth Cave National Park, Kentucky",
    "Mesa Verde National Park, Colorado",
    "Mount Rainer National Park, Washington",
    "North Cascades National Park, Washington",
    "Petrified Forest National Park, Arizona",
    "Pinnacles National Park, California",
    "Redwood National Park, California",
    "Rocky Mountain National Park, Colorado",
    "Saguaro National Park, Arizona",
    "Sequoia National Park, California",
    "Shenandoah National Park, Virginia",
    "Theodore Roosevelt National Park, North Dakota",
    "Virgin Islands National Park, U.S. Virgin Islands",
    "Voyageurs National Park, Minnesota",
    "Wind Cave National Park, South Dakota",
    "Wrangell-St. Elias National Park, Alaska",
    "Chaco Culture National Historical Park, New Mexico",
    "Everglades National Park, Florida",
    "Lassen Volcanic National Park, California",
    "Mammoth Cave National Park, Kentucky",
    "Saguaro National Park, Arizona",
    "Sequoia National Park, California",
    "Shenandoah National Park, Virginia",
    "Theodore Roosevelt National Park, North Dakota",
    "Virgin Islands National Park, U.S. Virgin Islands",
    "Voyageurs National Park, Minnesota",
    "Wind Cave National Park, South Dakota",
    "Wrangell-St. Elias National Park, Alaska",
    "Chaco Culture National Historical Park, New Mexico",
    "Gates of the Arctic National Park, Alaska",
    "Glacier Bay National Park, Alaska",
    "Guadalupe Mountains National Park, Texas",
    "Mesa Verde National Park, Colorado",
    "North Cascades National Park, Washington",
    "Petrified Forest National Park, Arizona",
    "Pinnacles National Park, California",
    "Redwood National Park, California",
    "Saguaro National Park, Arizona",
    "Sequoia National Park, California",
    "Shenandoah National Park, Virginia",
    "Theodore Roosevelt National Park, North Dakota",
    "Virgin Islands National Park, U.S. Virgin Islands",
    "Voyageurs National Park, Minnesota",
    "Wind Cave National Park, South Dakota",
    "Wrangell-St. Elias National Park, Alaska",
    "Chaco Culture National Historical Park, New Mexico",
    "Gates of the Arctic National Park, Alaska",
    "Glacier Bay National Park, Alaska",
    "Guadalupe Mountains National Park, Texas",
    "Mesa Verde National Park, Colorado",
    "North Cascades National Park, Washington",
    "Petrified Forest National Park, Arizona",
    "Pinnacles National Park, California",
    "Redwood National Park, California",
    "Saguaro National Park, Arizona",
    "Sequoia National Park, California",
    "Shenandoah National Park, Virginia",
    "Theodore Roosevelt National Park, North Dakota",
    "Virgin Islands National Park, U.S. Virgin Islands",
    "Voyageurs National Park, Minnesota",
    "Wind Cave National Park, South Dakota",
    "Wrangell-St. Elias National Park, Alaska",
    "Chaco Culture National Historical Park, New Mexico",
    "Gates of the Arctic National Park, Alaska",
    "Glacier Bay National Park, Alaska",
    "Guadalupe Mountains National Park, Texas",
    "Mesa Verde National Park, Colorado",
    "North Cascades National Park, Washington",
    "Petrified Forest National Park, Arizona",
    "Pinnacles National Park, California",
    "Redwood National Park, California",
    "Saguaro National Park, Arizona",
    "Sequoia National Park, California",
    "Shenandoah National Park, Virginia",
    "Theodore Roosevelt National Park, North Dakota",
    "Virgin Islands National Park, U.S. Virgin Islands",
    "Voyageurs National Park, Minnesota",
    "Wind Cave National Park, South Dakota",
    "Wrangell-St. Elias National Park, Alaska",
    "Chaco Culture National Historical Park, New Mexico",
    "Gates of the Arctic National Park, Alaska",
    "Glacier Bay National Park, Alaska",
    "Guadalupe Mountains National Park, Texas",
    "Mesa Verde National Park, Colorado",
    "North Cascades National Park, Washington",
    "Petrified Forest National Park, Arizona",
    "Pinnacles National Park, California",
    "Redwood National Park, California",
    "Saguaro National Park, Arizona",
    "Sequoia National Park, California",
    "Shenandoah National Park, Virginia",
    "Theodore Roosevelt National Park, North Dakota",
    "Virgin Islands National Park, U.S. Virgin Islands",
    "Voyageurs National Park, Minnesota",
    "Wind Cave National Park, South Dakota",
    "Wrangell-St. Elias National Park, Alaska",
    "Chaco Culture National Historical Park, New Mexico",
    "Gates of the Arctic National Park, Alaska",
    "Glacier Bay National Park, Alaska",
    "Guadalupe Mountains National Park, Texas",
    "Mesa Verde National Park, Colorado",
    "North Cascades National Park, Washington",
    "Petrified Forest National Park, Arizona",
    "Pinnacles National Park, California",
    "Redwood National Park, California",
    "Saguaro National Park, Arizona",
    "Sequoia National Park, California",
    "Shenandoah National Park, Virginia",
    "Theodore Roosevelt National Park, North Dakota",
    "Virgin Islands National Park, U.S. Virgin Islands",
    "Voyageurs National Park, Minnesota",
    "Wind Cave National Park, South Dakota",
    "Wrangell-St. Elias National Park, Alaska",
    "Chaco Culture National Historical Park, New Mexico",
    "Gates of the Arctic",
    "Banff National Park, Alberta, Canada",
    "Lake District National Park, England, United Kingdom",
    "Corcovado National Park, Costa Rica",
    "Kruger National Park, South Africa",
    "Torres del Paine National Park, Chile",
    "Queenstown, New Zealand",
    "Jasper National Park, Alberta, Canada",
    "Lake Wanaka, New Zealand",
    "Fiordland National Park, New Zealand",
    "Yosemite National Park, California, USA",
    "Rila National Park, Bulgaria",
    "Abel Tasman National Park, New Zealand",
    "Cape Range National Park, Western Australia",
    "Cairngorms National Park, Scotland, United Kingdom",
    "Mont-Tremblant National Park, Quebec, Canada",
    "Grampians National Park, Victoria, Australia",
    "Blue Mountains National Park, New South Wales, Australia",
    "Cinque Terre, Italy",
    "Jotunheimen National Park, Norway",
    "Wadi Rum, Jordan",
    "Plitvice Lakes National Park, Croatia",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Yosemite National Park, California, USA",
    "Lake District National Park, England, United Kingdom",
    "Corcovado National Park, Costa Rica",
    "Kruger National Park, South Africa",
    "Torres del Paine National Park, Chile",
    "Queenstown, New Zealand",
    "Jasper National Park, Alberta, Canada",
    "Lake Wanaka, New Zealand",
    "Fiordland National Park, New Zealand",
    "Rila National Park, Bulgaria",
    "Abel Tasman National Park, New Zealand",
    "Cape Range National Park, Western Australia",
    "Cairngorms National Park, Scotland, United Kingdom",
    "Mont-Tremblant National Park, Quebec, Canada",
    "Grampians National Park, Victoria, Australia",
    "Blue Mountains National Park, New South Wales, Australia",
    "Cinque Terre, Italy",
    "Jotunheimen National Park, Norway",
    "Wadi Rum, Jordan",
    "Plitvice Lakes National Park, Croatia",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland",
    "Karijini National Park, Western Australia",
    "Zion National Park, Utah, USA",
    "Ushuaia, Tierra del Fuego, Argentina",
    "Lake Bled, Slovenia",
    "Big Sur, California, USA",
    "Milford Sound, New Zealand",
    "Brecon Beacons National Park, Wales, United Kingdom",
    "Mount Rainier National Park, Washington, USA",
    "Joshua Tree National Park, California, USA",
    "Blue Lagoon, Iceland",
    "Purnululu National Park (Bungle Bungle Range), Western Australia",
    "The Dolomites, Italy",
    "Chirripó National Park, Costa Rica",
    "Snowdonia National Park, Wales, United Kingdom",
    "Aoraki/Mount Cook National Park, New Zealand",
    "Skaftafell National Park, Iceland",
    "Cape Tribulation, Queensland, Australia",
    "Vatnajökull National Park, Iceland" 

];
const seedDB = async () => {
    for (let m of loc ) {

        const getRandomImageFreq = Math.floor(Math.random() * 8 + 1);
        let arr = [];
        for (let i = 0; i < getRandomImageFreq; i++) {
            const getRandomIndex = Math.floor(Math.random() * 15);
            arr.push(obj[getRandomIndex]);
        }// To decide how many images a seeded campground should have.

        // const randomPlaces = Math.floor(Math.random() * loc.length);
        // const campPlace = loc[randomPlaces];

        const camp = new Campground({
            _id: new mongoose.Types.ObjectId(),
            title: `${sample(descriptors)} ${sample(places)}`,
            location: m,
            images: arr,
            price: sample30,
            author: '64c4d168d9daeac906ca5f63',
            description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Eos possimus enim consectetur harum"
                + "nihil commodi quia ipsum pariatur, fugit at corporis.Optionecessitatibus natus praesentium quis"
                + " blanditiis illum placeat officia."
        })
        const geoData = await geoCoder.forwardGeocode({
            query: camp.location,
            limit: 1
        }).send()

        camp.geometry = geoData.body.features[0].geometry;

        await camp.save();
    }
}

seedDB();   